<?php

$products =  [
    [
        'id' => 1,
        'title' => 'Agents of War: A History of Chemical and Biological Weapon',
        'author' => 'Edward M. Spiers',
        'description' => "Often described as the misuse of science, chemical and biological weapons have incurred widespread opposition over the years. Despite condemnation from the United Nations, governments, and the disarmament lobby, they remain very real options for rogue states and terrorists. In this new edition of Agents of War, Edward M. Spiers has expanded and updated this much-needed history with two new chapters on political poisoning and chemical weapons in the Middle East. Spiers breaks new ground by presenting his analysis in both historical and contemporary contexts, giving a comprehensive chronological account of why, where, and when such weapons were used or suspected to be deployed.",
        'img' => './public/theme/img/1.jpg',
        'price' => 11.99,
        'category' => 'bioterrorism',
        'type' => 'kindle',
        'available' => true,
        'sold' => 15,
        'stock' => 85,
        'barcode' => 9781234567897,
    ],
	[
        'id' => 2,
        'title' => '21 keys to develop a productivity plan & a productive mindset',
        'author' => 'Rob Willis',
        'description' => "Rob Willis will help you step by step on how to increase your personal productivity and achieve your personal goals. Overcome your bad habits to get more good habits, and you will also get tips to master managing your time. In THE 21 KEYS TO DEVELOP A PRODUCTIVITY PLAN & A PRODUCTIVE MINDSET, you'll discover: How to increase your productivity. Regardless of whether in the home or at work. How to build a productive mindset and plan your day. Time management strategies; the right way to a productive day. How you can declutter your life and beat the enemies. How to clear your mind. Resting and eating - Helping You to Remain Productive How you'll have more recreation time. Recreation time implies less pressure and more prominent energy in your life.
        strategies to make yourself more productive by making only a couple of changes. Tips and tricks that will assist you to complete more in less time. PLUS, YOU'LL RECEIVE A Bonus: 12 chapters MINDFUL MEDITATION SECRET that will help you a lot to improve your life, decrease your pressure and stress. In case you're tired and stressed out from life or your work, grab your copy of 21 KEYS TO DEVELOP A PRODUCTIVITY PLAN & A PRODUCTIVE MINDSET today! Start taking action to overcome your bad habits and improve your time management.",
        'img' => './public/theme/img/2.jpg',
        'price' => 2.35,
        'category' => 'psychology',
        'type' => 'kindle',
        'available' => true,
        'sold' => 22,
        'stock' => 28,
        'barcode' => 5263825213272 ,
    ],
    [
        'id' => 3,
        'title' => 'American antrax',
        'author' => 'Jeanne Guillemin',
        'description' => "It was the most complex case in FBI history. In what became a seven-year investigation that began shortly after 9/11—with America reeling from the terror attacks of al Qaeda—virulent anthrax spores sent through the mail killed Bob Stevens, a Florida tabloid photo editor. His death and, days later, the discovery in New York and Washington, D.C. of letters filled with anthrax sent shock waves through the nation. Federal agencies were blindsided by the attacks, which eventually killed five people. Taken off guard, the FBI struggled to combine on-the-ground criminal investigation with progress in advanced bioforensic analyses of the letters' contents. While the criminal eluded justice, disinformation swirled around the letters, erroneously linking them to Iraq's WMD threat and foreign bioterrorism. Without oversight, billions were lavished on biomedical defenses against anthrax and other exotic diseases. Worst of all, faith in federal justice faltered. American Anthrax is a gripping tale of terror, intrigue, madness, and cover-up.",
        'img' => './public/theme/img/3.jpg',
        'price' => 14.97,
        'category' => 'bioterrorism',
        'type' => 'hardcover',
        'available' => true,
        'sold' => 55,
        'stock' => 15,
        'barcode' => 6617349967874,
    ],
    [
        'id' => 4,
        'title' => 'Our inner conflicts: A Constructive Theory of Neurosis',
        'author' => 'Karen Horney, M.D.',
        'description' => 'Here Karen Horney develops a dynamic theory of neurosis centered on the basic conflict among attitudes of "moving forward" "moving against," and "moving away from" people. Unlike Freud, Horney does not regard neurosis as rooted in instinct. In her words, her theory is constructive because "it allows us for the first time to tackle and resolve neurotic hopelessness. . . . Neurotic conflicts cannot be resolved by rational decision. . . . But [they] can be resolved by changing the conditions within the personality that brought them into being."',
        'img' => './public/theme/img/4.jpg',
        'price' => 17.95,
        'category' => 'psychology',
        'type' => 'paperback',
        'available' => true,
        'sold' => 75,
        'stock' => 25,
        'barcode' => 4832831929472 ,
    ],
    [
        'id' => 5,
        'title' => 'Dreaming in Dark Times: Six Exercises in Political Thought',
        'author' => 'Sharon Sliwinski',
        'description' => "What do dreams manage to say—or indeed, show—about human experience that is not legible otherwise? Can the disclosure of our dream-life be understood as a form of political avowal? To what does a dream attest? And to whom? Blending psychoanalytic theory with the work of such political thinkers as Hannah Arendt and Michel Foucault, Sharon Sliwinski explores how the disclosure of dream-life represents a special kind of communicative gesture—a form of unconscious thinking that can serve as a potent brand of political intervention and a means for resisting sovereign power. Each chapter centers on a specific dream plucked from the historical record, slowly unwinding the significance of this extraordinary disclosure. From Wilfred Owen and Lee Miller to Frantz Fanon and Nelson Mandela, Sliwinski shows how each of these figures grappled with dream-life as a means to conjure up the courage to speak about dark times. Here dreaming is defined as an integral political exercise—a vehicle for otherwise unthinkable thoughts and a wellspring for the freedom of expression. Dreaming in Dark Times defends the idea that dream-life matters—that attending to this thought-landscape is vital to the life of the individual but also vital to our shared social and political worlds.",
        'img' => './public/theme/img/5.jpg',
        'price' => 117.42,
        'category' => 'political science',
        'type' => 'hardcover',
        'available' => true,
        'sold' => 3,
        'stock' => 27,
        'barcode' => 7467285504176 ,
    ],
    [
        'id' => 6,
        'title' => 'Biosecurity and bioterrorism: Containing and Preventing Biological Threats',
        'author' => 'Jeffrey Ryan, Jan Glarum',
        'description' => 'Biosecurity and Bioterrorism is the first book to take a holistic approach to biosecurity with coverage of pathogens, prevention and response methodology. The book is organized into four thematic sections: Part I provides a conceptual understanding of biowarfare, bioterrorism and the laws we have to counteract this; Part II investigates known bioagents and the threat from emerging diseases; Part III focuses on agricultural terrorism and food security; Part IV outlines international, US, and local initiatives for biodefense and biosecurity. Case studies illustrate biodefense against both intentional terrorism and natural outbreaks. The authors bring an extraordinary combination of experience in academia and the clinical world, as well as real-world experience in technical and practical matters, to their writing. They make technical material clear and fascinating for readers with a basic knowledge of biology. Ryan and Glarum address the hazards in the context of vulnerability assessments and the planning strategies government and industry can take to prepare for and respond to such events.',
        'img' => './public/theme/img/6.jpg',
        'price' => 19.82,
        'category' => 'bioterrorism',
        'type' => 'hardcover',
        'available' => false,
        'sold' => 105,
        'stock' => 20,
        'barcode' => 5744724731528 ,
    ],
	[
        'id' => 7,
        'title' => 'Religions, values, and peak-experineces',
        'author' => 'Abragamh Maslow',
        'description' => 'Proposing religious experience as a legitimate subject for scientific investigation, Maslow studies the human need for spiritual expression.',
        'img' => './public/theme/img/7.jpg',
        'price' => 1.19,
        'category' => 'psychology',
        'type' => 'kindle',
        'available' => true,
        'sold' => 13,
        'stock' => 67,
        'barcode' => 3873710182418,
    ],
    [
        'id' => 8,
        'title' => "The Art of War",
        'author' => 'Sun Tzu',
        'description' => "Sun-tzu's Art of War is almost certainly the most famous study of strategy ever written. This treatise has been credited with influencing some of the most legendary military operations. Beyond the battlefield, people far and wide have long turned to Art of War for advice on how to succeed in various competitive situations, and companies around the world now make this book required reading for their executives. In this translation, Chinese warfare scholar Ralph D. Sawyer places Art of War in its proper historical context, outlining several battles that Sun-tzu either conducted or that may have influenced him, and offers an edition that is uniquely accurate and accessible.",
        'img' => './public/theme/img/8.jpg',
        'price' => 9.99,
        'category' => 'plitical science',
        'type' => 'paperback',
        'available' => true,
        'sold' => 33,
        'stock' => 67,
        'barcode' => 8971439816123,
    ],
    [
        'id' => 9,
        'title' => 'Bioimperialism: Disease, Terror, and the Construction of National Fragility',
        'author' => "Gwen Shuni D'Arcangelis",
        'description' => 'Bio-Imperialism focuses on an understudied dimension of the war on terror: the fight against bioterrorism. This component of the war enlisted the biosciences and public health fields to build up the U.S. biodefense industry and U.S. global disease control. The book argues that U.S. imperial ambitions drove these shifts in focus, aided by gendered and racialized discourses on terrorism, disease, and science. These narratives helped rationalize American research expansion into dangerous germs and bioweapons in the name of biodefense and bolstered the U.S. rationale for increased interference in the disease control decisions of Global South nations. Bio-Imperialism is a sobering look at how the war on terror impacted the world in ways that we are only just starting to grapple with.',
        'img' => './public/theme/img/9.jpg',
        'price' => 32.00,
        'category' => 'bioterrorism',
        'type' => 'kindle',
        'available' => true,
        'sold' => 99,
        'stock' => 1,
        'barcode' => 5861409130373,
    ],
    [
        'id' => 10,
        'title' => 'Critique of Psychoanalytic Concepts and Theories',
        'author' => 'B.F.Skinner',
        'description' => "Classic article originally published in 1954 in which B.F Skinner critically evaluates Sigmund Freud's contribution to Western thought. In particular Freud's attempt to infer how the mental apparatus is constructed and what forces interplay and counteract in it. Critique of Psychoanalytic Concepts and Theories (Kindle edition) forms part of an initiative by the website www.all-about-psychology.com to make important, insightful and engaging psychology publications widely available.",
        'img' => './public/theme/img/10.jpg',
        'price' => 3.59,
        'category' => 'psychology',
        'type' => 'kindle',
        'available' => true,
        'sold' => 15,
        'stock' => 85,
        'barcode' => 9546131066369,
    ],
    [
        'id' => 11,
        'title' => 'A Historical Review On A Biological Warfare Weapon',
        'author' => 'Ira Devost',
        'description' => "An elite PMC, Shadow Company operates outside the boundaries of the original Armistice. Forged from the fires of in-fighting between the Coalition and the Allegiance, Shadow Company has a framework and agenda all of their own. A top secret military team is sent to rescue a research scientist with info on a biological warfare weapon. Read more about Shadow Company and their fight for survival in the heart of Kolkata.",
        'img' => './public/theme/img/11.jpg',
        'price' => 0.00,
        'category' => 'bioterrorism',
        'type' => 'kindle',
        'available' => true,
        'sold' => 246,
        'stock' => 4,
        'barcode' => 4889337586817,
    ],
	[
        'id' => 12,
        'title' => 'Bioterrorism: Prevention, Preparedness And Protection',
        'author' => 'J.V.Borelli',
        'description' => "A bioterrorism attack is the deliberate release of viruses, bacteria, or other germs (agents) used to cause illness or death in people, animals, or plants. These agents are typically found in nature, but it is possible that they could be changed to increase their ability to cause disease, make them resistant to current medicines, or to increase their ability to be spread into the environment. Biological agents can be spread through the air, through water, or in food. Terrorists may use biological agents because they can be extremely difficult to detect and do not cause illness for several hours to several days. Some bioterrorism agents, like the smallpox virus, can be spread from person to person and some, like anthrax, can not. This new book presents new analyses on the prevention of, preparedness for and protection from.",
        'img' => './public/theme/img/12.jpg',
        'price' => 224.60,
        'category' => 'bioterrorism',
        'type' => 'hardcover',
        'available' => true,
        'sold' => 133,
        'stock' => 67,
        'barcode' => 1706658627670,
    ],
    [
        'id' => 13,
        'title' => 'A Summary of Propaganda',
        'author' => 'Edward Berneys',
        'description' => "Edward Bernays, the father of public relations, explains what propaganda is and how it is applied on society. It's an explanation of how an elite's class runs the world through the change of public opinion with propaganda as a tool. Edward Bernays, just like Tesla and any other figure that doesn't make it to the history books, is as important as the history books. Everyone owes it to himself to listen to this book. Save time on the go with the compact format and concise summary. Explore key quotations from the book!",
        'img' => './public/theme/img/13.jpg',
        'price' => 5.99,
        'category' => 'political science',
        'type' => 'paperback',
        'available' => true,
        'sold' => 78,
        'stock' => 100,
        'barcode' => 9265146806560,
    ],
    [
        'id' => 14,
        'title' => 'Bioterrorism: A guide for hospital preparedness',
        'author' => 'Joseph R. Masci',
        'description' => "In the battle against bioterrorism, one of the greatest challenges is finding the ideal balance between complacency and overreaction. The goal is to be so well prepared that we can prevent catastrophic outcomes in the event of a bioterrorist attack, while strengthening our ability to prevent and treat naturally-occurring infectious diseases. Bioterrorism: A Guide for Hospital Preparedness provides critical guidelines for health providers on effectively preparing for bioterrorism. The book presents information on all aspects of dealing with bioterrorism including the likeliest biological agents to be used, means of determining that an attack is taking place, diagnosis and management of specific diseases, and mechanisms of reporting to public health authorities. The text reviews cooperative planning for private practitioners, methods for protecting hospital and office staff and other patients in the event of an attack, approaches to handling the psychological effects of terrorism, special considerations concerning the care of children, and strategies for answering questions posed by the public and the media. It also includes data from national and regional exercises in assessing preparedness, with suggestions for implementing lessons learned from these exercises. With bioterrorism on the fine line between risk and reality, it is essential for health care providers to be properly equipped for every situation. This comprehensive guide features solid strategies for establishing and maintaining an attainable level of preparation in the ever-present risk of bioterrorism.",
        'img' => './public/theme/img/14.jpg',
        'price' => 217.48,
        'category' => 'bioterrorism',
        'type' => 'hardcover',
        'available' => true,
        'sold' => 88,
        'stock' => 12,
        'barcode' => 5266264512932,
    ],
    [
        'id' => 15,
        'title' => 'Resilience',
        'author' => 'Linda Graham',
        'description' => "Whether it's a critical comment from the boss or a full-blown catastrophe, life continually dishes out challenges. Resilience is the learned capacity to cope with any level of adversity, from the small annoyances of daily life to the struggles and sorrows that break our hearts. Resilience is essential for surviving and thriving in a world full of troubles and tragedies, and it is completely trainable and recoverable — when we know how. In Resilience, Linda Graham offers clear guidance to help you develop somatic, emotional, relational, and reflective intelligence — the skills you need to confidently and effectively cope with life's inevitable challenges and crises.",
        'img' => './public/theme/img/15.jpg',
        'price' => 9.99,
        'category' => 'psychology',
        'type' => 'paperback',
        'available' => true,
        'sold' => 23,
        'stock' => 27,
        'barcode' => 6493030084170,
    ],
    [
        'id' => 16,
        'title' => 'Human Security: Theory and Action',
        'author' => 'David Andersen-Rodgers',
        'description' => "Human security refers in its broadest sense to the protection of individuals from harm. Human Security: Theory and Action explores the theory and application of concepts central to this notion of security. It examines the conceptual roots of human security, connecting its origins to its applications and challenges in war and peacetime. With a unique focus on the evolving notion of responsibility for security, the text introduces the critical questions and priorities that underpin policies and actions.
        The text is organized around four sections. The introduction offers an overview of human security and its basic tenets and historical foundations. The second section focuses on human security in armed conflict and post-conflict reconstruction, discussing such issues as the doctrine of Responsibility to Protect (R2P), peacekeeping and peace negotiation processes, and humanitarian assistance. The third section identifies the long-term issues that are necessary for a durable human security, including human rights, food security, poverty, gender equality, health security, and environmental sustainability. The final section applies the concepts introduced in the book to twenty-first century concerns and offers insights on turning theory into action.
        Integrated into the text are many case studies to broaden the student's awareness beyond the conflicts and issues that dominate the media. By balancing theoretical explanations with concrete illustrative cases, both historical and contemporary, the text provides intellectually challenging and intrinsically interesting material and offers a unique, comprehensive introduction human security in war and peace.",
        'img' => './public/theme/img/16.jpg',
        'price' => 25.95,
        'category' => 'human security',
        'type' => 'book',
        'available' => true,
        'sold' => 85,
        'stock' => 155,
        'barcode' => 1958678291971,
    ],
	[
        'id' => 17,
        'title' => 'Bioterrorism and Infectious Agents',
        'author' => 'I.W.Fong',
        'description' => "Compiled by two leading experts in the field, this volume provides a concise, timely, and authoritative review of some of the most problematic infections of the new century. It presents issues and new ideas for preventing and controlling infectious diseases.",
        'img' => './public/theme/img/17.jpg',
        'price' => 32.78,
        'category' => 'bioterrorism',
        'type' => 'kindle',
        'available' => true,
        'sold' => 15,
        'stock' => 100,
        'barcode' => 7156586802293,
    ],
    [
        'id' => 18,
        'title' => 'The Outsiders',
        'author' => 'S.E.Hinton',
        'description' => "No one ever said life was easy. But Ponyboy is pretty sure that he's got things figured out. He knows that he can count on his brothers, Darry and Sodapop. And he knows that he can count on his friends—true friends who would do anything for him, like Johnny and Two-Bit. But not on much else besides trouble with the Socs, a vicious gang of rich kids whose idea of a good time is beating up on “greasers” like Ponyboy. At least he knows what to expect—until the night someone takes things too far. The Outsiders is a dramatic and enduring work of fiction that laid the groundwork for the YA genre. S. E. Hinton's classic story of a boy who finds himself on the outskirts of regular society remains as powerful today as it was the day it was first published. 'The Outsiders transformed young-adult fiction from a genre mostly about prom queens, football players and high school crushes to one that portrayed a darker, truer world.' —The New York Times",
        'img' => './public/theme/img/18.jpg',
        'price' => 5.89,
        'category' => 'psychology',
        'type' => 'paperback',
        'available' => true,
        'sold' => 55,
        'stock' => 45,
        'barcode' => 8714383419231,
    ],
    [
        'id' => 19,
        'title' => 'Small-Scale Terrorist Attacks Using Chemical And Biological Agents',
        'author' => 'Dana A. Shea',
        'description' => "This book presents a means of assessing the relative threat from terrorist-use of individual chemical, biological, and toxin agents. It focuses on small-scale, targeted chemical and biological attacks, rather than mass-casualty attacks. The framework considers the elements of access, public health impact, medical treatment, prophylaxis, and dissemination. Other factors that may affect potential use by terrorists include the range of lethality, covert employment of an agent, and the availability of dual-use technologies. The results of this book may be useful in addressing the threat these agents pose, for example by indicating priorities for countermeasure funding. Other uses include weighing the potential effectiveness of policy options, assessing threat reduction approaches to specific agents, and serving as a resource for developing other specialised frameworks.",
        'img' => './public/theme/img/19.jpg',
        'price' => 144.29,
        'category' => 'bioterrorism',
        'type' => 'hardcover',
        'available' => true,
        'sold' => 95,
        'stock' => 5,
        'barcode' => 9931199885627,
    ],
    [
        'id' => 20,
        'title' => 'Public Opinion',
        'author' => 'Walter Lippmann',
        'description' => "First published in 1922, “Public Opinion” is the fascinating study of the role of citizens in a democracy by Walter Lippmann, an American writer, reporter and political commentator. Lippmann’s notable career spanned decades and produced some of the most important journalism in American history. He was the first to introduce the concept of the Cold War, received many awards, including two Pulitzer Prizes, and wrote thousands of articles and columns, earning him the title of the “Great Elucidator”. “Public Opinion” is Lippmann’s assessment of a functional democratic government and the role that citizens play in the democracy. Lippmann examines the dilemmas presented in revolutionary periods of history and raises doubts on the ability of citizens to effectively govern themselves. He draws important attention to the media’s role in shaping public perceptions and opinions and presciently warns against the power of propaganda. Lippmann’s work exploring modern democracy, how it functions, and what situations most threaten its success have made “Public Opinion” a staple in the field of political science. Lippmann’s work was far ahead of its time in understanding the dangers of propaganda and his conclusions remain relevant and thought-provoking nearly a century later. This edition is printed on premium acid-free paper.",
        'img' => './public/theme/img/20.jpg',
        'price' => 8.99,
        'category' => 'political science',
        'type' => 'paperback',
        'available' => false,
        'sold' => 300,
        'stock' => 0,
        'barcode' => 1510831485657,

    ],
    [
        'id' => 21,
        'title' => 'Floodlines: Community and Resistance from Katrina to the Jena Six',
        'author' => 'Jordan Flaherty',
        'description' => "Organizers, activists, artists and community members share their struggles in New Orleans before and after Hurricane Katrina. Floodlines is a firsthand account of community, culture, and resistance in New Orleans. The book weaves the stories of gay rappers, Mardi Gras Indians, Arab and Latino immigrants, public housing residents, and grassroots activists in the years before and after Katrina. From post-Katrina evacuee camps to torture testimony at Angola Prison to organizing with the family members of the Jena Six, Floodlines tells the stories behind the headlines from an unforgettable time and place in history.",
        'img' => './public/theme/img/21.jpg',
        'price' => 2.99,
        'category' => 'disasters',
        'type' => 'kindle',
        'available' => true,
        'sold' => 215,
        'stock' => 15,
        'barcode' => 2586855413777,
    ],
	[
        'id' => 22,
        'title' => 'Behavior and the Concept of Mental Disease',
        'author' => 'John B. Watson',
        'description' => "First published in 1916 this classic article by 'father of behaviorism' John B Watson provides an excellent early example of the author's attempt to move away from the language of psychoanalysis towards a more scientific psychological terminology. Behavior and the Concept of Mental Disease (Kindle edition) forms part of an initiative by the website www.all-about-psychology.com to make important, insightful and engaging psychology publications widely available.",
        'img' => './public/theme/img/22.jpg',
        'price' => 0.99,
        'category' => 'psychology',
        'type' => 'kindle',
        'available' => true,
        'sold' => 113,
        'stock' => 76,
        'barcode' => 6569842331493,
    ],
    [
        'id' => 23,
        'title' => 'The Sinking of the Titanic and Great Sea Disasters',
        'author' => 'Logan Marshall',
        'description' => 'The RMS Titanic, a British passenger liner operated by the White Star Line, struck an iceberg on her maiden voyage from Southampton to New York City on April 15, 1912. She was considered "unsinkable", but in less than 3 hours, she sank. Of the estimated 2,224 passengers and crew aboard, more than 1,500 died, making the sinking the deadliest peacetime sinking of a cruise ship to date. RMS Titanic was the largest ship afloat at the time she entered service and was the second of three Olympic-class ocean liners operated by the White Star Line. She was under the command of Captain Edward Smith, who went down with the ship. The ocean liner carried some of the wealthiest people in the world, as well as hundreds of emigrants from Great Britain and Ireland, Scandinavia and elsewhere throughout Europe. This book is a riveting first-hand account of the tragedy.You can even see drawings by passenger Jack Thayer who was the inspiration for Jack Dawson in the popular movie Titanic.',
        'img' => './public/theme/img/23.jpg',
        'price' => 31.96,
        'category' => 'disaster',
        'type' => 'hardcover',
        'available' => true,
        'sold' => 36,
        'stock' => 150,
        'barcode' => 1989297195406,
    ],
    [
        'id' => 24,
        'title' => 'Human Security in a Borderless World',
        'author' => 'Derek S. Reverson & Kathleen A. Mahoney-Norris',
        'description' => "To fully understand contemporary security studies, we must move beyond the traditional focus on major national powers and big wars. Modern threats to security include issues such as globalization, climate change, pandemic diseases, endemic poverty, weak and failing states, transnational narcotics trafficking, piracy, and vulnerable information systems. Human Security in a Borderless World offers a fresh, detailed examination of these challenges that threaten human beings, their societies, and their governments today. Authors Derek S. Reveron and Kathleen A. Mahoney-Norris provide a thought-provoking exploration of civic, economic, environmental, maritime, health, and cyber security issues in this era of globalization, including thorough consideration of the policy implications for the United States. They argue that human security is now national security.
        This timely and engaging book is an essential text for today's courses on security studies, foreign policy, international relations, and global issues. Features include three special sections in each chapter that explain potential counterarguments about the topic under consideration; explore the policy debates that dominate the area of study; and illuminate concrete examples of security threats. Richly illustrated and accessibly written, Human Security in a Borderless World is designed to encourage critical thinking and bring the material to life for students.",
        'img' => './public/theme/img/24.jpg',
        'price' => 102.79,
        'category' => 'human security',
        'type' => 'hardcover',
        'available' => true,
        'sold' => 73,
        'stock' => 30,
        'barcode' => 3683596884329,
    ],
    [
        'id' => 25,
        'title' => 'The Rape of the Mind',
        'author' => "Joost A.M.Meerloo",
        'description' => "In 1933 Meerloo began to study the methods by which systematic mental pressure brings people to abject submission, and by which totalitarians imprint their subjective 'truth' on their victims' minds. In 'The Rape of the Mind' he goes far beyond the direct military implications of mental torture to describing how our own culture unobtrusively shows symptoms of pressurizing people's minds. He presents a systematic analysis of the methods of brainwashing and mental torture and coercion, and shows how totalitarian strategy, with its use of mass psychology, leads to systematized 'rape of the mind'. He describes the new age of cold war with its mental terror, verbocracy, and semantic fog, the use of fear as a tool of mass submission and the problem of treason and loyalty, so loaded with dangerous confusion.",
        'img' => './public/theme/img/25.jpg',
        'price' => 19.25,
        'category' => 'psychology',
        'type' => 'paperback',
        'available' => true,
        'sold' => 99,
        'stock' => 100,
        'barcode' => 6306441753762,
    ],
];

/* * * mysql hostname ** */
$hostname = "localhost";
/* * * mysql username ** */
$username = "root";
/* * * mysql password ** */
$password = "";
/* * * mysql database name ** */
$database = "bookshop";

try {
    $connection = new PDO("mysql:host=$hostname;dbname=$database;charset=utf8", $username, $password);
    $connection->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    foreach ($products as $product) {
        $sqlQueryString = "INSERT INTO sepca_products (title, author, description, price, stock, sold, category, type, img, status, barcode)"
                        . " VALUES (" . ":title" . ", " . ":author" . "," . ":description" . ", " . ":price" . ", " . ":stock" . "," . ":sold" . "," . ":category" . "," . ":type" . ", " . ":img" . ", "
                        . ":status" . ", " . ":barcode" . ")";
        $statement = $connection->prepare($sqlQueryString);
        $params = [
            'title' => $product["title"],
            'author' => $product["author"],
            'description' => $product["description"],
            'price' => $product["price"],
            'stock' => $product["stock"],
            'sold' => $product["sold"],
            'category' => $product["category"],
            'type' => $product["type"],
            'img' => $product["img"],
            'status' => $product["available"],
            'barcode' => $product["barcode"],
        ];
        $status = $statement->execute($params);
    }
} catch (PDOException $exception) {
    echo "Something went wrong: " . $exception->getMessage() . "<br>";
}
